### ISSUE TITLE
[ERROR] ERR_OUT_OF_RANGE With Heavy MDL FIle

### ISSUE THREAD

**Issue by BlackYuzia** [LordVonAdel/structron#1] opened 2021-07-20 13:44 UTC
Hello @LordVonAdel 
How I saw you a developer of `structorn` and `source-mdl` pkgs.

When I try read too big mdl file, I get range out error. What we could to do with that?
```js
(node:11292) UnhandledPromiseRejectionWarning: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 705142. Received 16778226
    at boundsError (internal/buffer.js:83:9)
    at Buffer.readUInt8 (internal/buffer.js:249:5)
    at Object.read (hello-world\node_modules\structron\types.js:156:21)
    at Struct.read (hello-world\node_modules\structron\index.js:143:39)
    at Struct.read (hello-world\node_modules\structron\index.js:157:22)
    at Struct.read (hello-world\node_modules\structron\index.js:157:22)
    at Struct.read (hello-world\node_modules\structron\index.js:157:22)
    at Struct.read (hello-world\node_modules\structron\index.js:157:22)
    at Struct.read (hello-world\node_modules\structron\index.js:157:22)
    at Struct.read (hello-world\node_modules\structron\index.js:157:22)
```

```js
// index.js
const model = new MDL();
model.import({
                    mdlData: mdlFile, // 154KB
                    vvdData: vvdFile,
                    vtxData: vtxFile
                })
```

**File size: 154KB**

I also get sometimes another errors:
```
 Errors (1):
  root.hitboxes[0].hitboxes[0].name: The value of "offset" is out of range. It must be >= 0 and <= 1563. Received 2128
  ```

**Comment by LordVonAdel** [comment] 2021-07-20 14:27
Hey @BlackYuzia 
From what game are the model on which the errors occurs?

I think the problem is related to `source-mdl` and not `structron`. Can you provide an example model by file or the name of the model from a game?

**Comment by BlackYuzia** [comment] 2021-07-20 14:28
CSGO, I actualy can give you that model, where I should upload that model
and only mdl file or any else too?

**Comment by LordVonAdel** [comment] 2021-07-20 14:36
I need all three files. MDL, VTX and VVD.

You can add the files in a comment for this issue as zip.

Or if that doesn't work, you can use https://wetransfer.com/ . Just drop the files in an set "Get transfer link" in the menu that opens with the three dots. Post the link here in the issue.

**Comment by BlackYuzia** [comment] 2021-07-20 14:38
[model (4 files, without materials and arms).zip](https://github.com/LordVonAdel/structron/files/6849151/model.4.files.without.materials.and.arms.zip)

@LordVonAdel done

**Comment by LordVonAdel** [comment] 2021-07-20 14:41
Thanks. I will look into it.

**Comment by LordVonAdel** [comment] 2021-07-31 00:16
Fixed in https://github.com/LordVonAdel/source-mdl/commit/b84c01d46feff071a74bb9fda510f10c622a260f

**Closed as completed by LordVonAdel** 2021-07-31 00:16 UTC
